# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 508e6ba14da4ec66cf281f788d4d342b6ce351fdd493d38f6978a6b28ac5b0f90e919724603d2e27a21129ef5db2a75dbd2771cdeab85f444c82cda287a48588

test:
  secret_key_base: 2d2b9cbcce2954450496841dc445de9c484f90b15e6fda6bab6db0e607aa81a826bd8278b45379cc71567a8c1b73f36abc65c227246887763d22ea088866fcf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
